on: [push]

name: Linter

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: actions/setup-ruby@v1

      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          gem install rubocop rubocop-performance rubocop-rspec --no-document

      - name: Run linter
        run: |
          rubocop
