name: Linter

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: actions/setup-ruby@v1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run linter
        run: |
          bundle exec rubocop
